sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: liushijiu
    password: liushijiu69
  redis:
    port: 6379
    database: 2
    host: localhost
#    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-liushijiu
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  wechat:
    appid: wx3b2cfa4ac5ecc13c
    secret: 4bbaf6fa6de247d10c0d0beeca8f8a86